import Head from 'next/head'
import Footer from './components/Footer'
import Hero from './components/Hero'
import Navbar from './components/Navbar'
import Services from './components/Services'
import Testimonial from './components/Testimonial'
import Work from './components/Work'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>PemudaCoding: Learning coding center 1st in the world</title>
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="mt-14 ">
        <Hero />
        <Services />
        <Work />
        <Testimonial />
      </main>

      <footer>
        <Footer/>
      </footer>
    </div>
  )
}
